Create separete Contact App

diff --git a/make-prodenv b/make-prodenv
--- a/make-prodenv
+++ b/make-prodenv
@@ -8,20 +8,20 @@ echo
 
 read -p "Are you sure you want to continue? (yes/no) "
 if [ "$REPLY" != "yes" ]; then
-   exit
+   exit 0
 fi
 echo
 
 read -p "Are you sure? (type production to continue) "
 if [ "$REPLY" != "production" ]; then
-   exit
+   exit 0
 fi
 echo
 
 read -p "Do you want to pull update source code from the repository? (yes/no) "
 if [ "$REPLY" == "yes" ]; then
 	echo
-	echo "Pull most recent ..."
+	echo "Pulling most recent ..."
 	echo
 	git pull
 	echo "Done"
@@ -30,40 +30,65 @@ echo
 
 echo "Creating virtual enviroment (venv) ..."
 virtualenv --python=python3 venv
+if [ ! $? -eq 0 ]; then
+   exit 1
+fi
 echo "Done"
 
 echo "Activating virtual enviroment (venv) ..."
 source venv/bin/activate
+if [ "$VIRTUAL_ENV" == "" ]; then
+   exit 1
+fi
 echo "Done"
 
 echo "Upgrading pip ..."
 pip install --upgrade pip
+if [ ! $? -eq 0 ]; then
+   exit 1
+fi
 echo "Done"
 
 echo "Installing prerequisites ..."
 pip install -r requirements.txt
+if [ ! $? -eq 0 ]; then
+   exit 1
+fi
+echo "Done"
+
+echo "Checking Secrets ..."
+if [ ! -f secrets.json ]; then
+   echo "Fail"; echo; exit 1
+fi
 echo "Done"
 
 echo "Applying migrations ..."
 mkdir -p data
 python manage.py migrate --settings=config.settings.prod
+if [ ! $? -eq 0 ]; then
+   exit 1
+fi
 echo "Done"
 
 echo "Collecting static files ..."
 mkdir -p static
-mkdir -p media
 python manage.py collectstatic --clear --noinput --settings=config.settings.prod
+if [ ! $? -eq 0 ]; then
+   exit 1
+fi
 python manage.py collectstatic --noinput --settings=config.settings.prod
+if [ ! $? -eq 0 ]; then
+   exit 1
+fi
 echo "Done"
 
 echo "Setting permissions ..."
-sudo chgrp www-data -R data/ media/
+sudo chgrp www-data -R data/
 chmod 664 data/*
 chmod 775 data
-chmod 755 media
 echo "Done"
 
 echo "Environment Ready!"
 echo
 
-# 2017.11.01-DEA
+# 2017.11.08-DEA
